/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccreditationStorage } from "./AccreditationStorage";
export type { CertificateStorage } from "./CertificateStorage";
