/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as endpoints from "./endpoints";
export type { endpoints };
import type * as nft from "./nft";
export type { nft };
import type * as storage from "./storage";
export type { storage };
