/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccreditationNFT } from "./AccreditationNFT";
export type { CertificateNFT } from "./CertificateNFT";
