/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type ApplicantStruct = {
  name: PromiseOrValue<string>;
  applicantAddress: PromiseOrValue<string>;
  createdAt: PromiseOrValue<BigNumberish>;
};

export type ApplicantStructOutput = [string, string, BigNumber] & {
  name: string;
  applicantAddress: string;
  createdAt: BigNumber;
};

export interface ApplicantEndpointInterface extends utils.Interface {
  functions: {
    "getApplicantByAddress(address)": FunctionFragment;
    "registerApplicant(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getApplicantByAddress" | "registerApplicant"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getApplicantByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerApplicant",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getApplicantByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerApplicant",
    data: BytesLike
  ): Result;

  events: {
    "RegisterApplicant(address,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RegisterApplicant"): EventFragment;
}

export interface RegisterApplicantEventObject {
  applicantAddress: string;
  name: string;
  createdAt: BigNumber;
}
export type RegisterApplicantEvent = TypedEvent<
  [string, string, BigNumber],
  RegisterApplicantEventObject
>;

export type RegisterApplicantEventFilter =
  TypedEventFilter<RegisterApplicantEvent>;

export interface ApplicantEndpoint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ApplicantEndpointInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getApplicantByAddress(
      applicantAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[ApplicantStructOutput]>;

    registerApplicant(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getApplicantByAddress(
    applicantAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ApplicantStructOutput>;

  registerApplicant(
    name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getApplicantByAddress(
      applicantAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ApplicantStructOutput>;

    registerApplicant(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RegisterApplicant(address,string,uint256)"(
      applicantAddress?: null,
      name?: null,
      createdAt?: null
    ): RegisterApplicantEventFilter;
    RegisterApplicant(
      applicantAddress?: null,
      name?: null,
      createdAt?: null
    ): RegisterApplicantEventFilter;
  };

  estimateGas: {
    getApplicantByAddress(
      applicantAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerApplicant(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getApplicantByAddress(
      applicantAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerApplicant(
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
