/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccreditationEndpoint } from "./AccreditationEndpoint";
export type { ApplicantEndpoint } from "./ApplicantEndpoint";
export type { CertificateEndpoint } from "./CertificateEndpoint";
export type { IssuerEndpoint } from "./IssuerEndpoint";
