/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type IssuerStruct = {
  name: PromiseOrValue<string>;
  issuerAddress: PromiseOrValue<string>;
  description: PromiseOrValue<string>;
  logoUrl: PromiseOrValue<string>;
  createdAt: PromiseOrValue<BigNumberish>;
};

export type IssuerStructOutput = [string, string, string, string, BigNumber] & {
  name: string;
  issuerAddress: string;
  description: string;
  logoUrl: string;
  createdAt: BigNumber;
};

export interface IssuerEndpointInterface extends utils.Interface {
  functions: {
    "getIssuerByAddress(address)": FunctionFragment;
    "registerIssuer(address,string,string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getIssuerByAddress" | "registerIssuer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getIssuerByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIssuer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getIssuerByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIssuer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IssuerEndpoint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IssuerEndpointInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getIssuerByAddress(
      issuerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[IssuerStructOutput]>;

    registerIssuer(
      issuerAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      logoUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getIssuerByAddress(
    issuerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<IssuerStructOutput>;

  registerIssuer(
    issuerAddress: PromiseOrValue<string>,
    name: PromiseOrValue<string>,
    description: PromiseOrValue<string>,
    logoUrl: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getIssuerByAddress(
      issuerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IssuerStructOutput>;

    registerIssuer(
      issuerAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      logoUrl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getIssuerByAddress(
      issuerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerIssuer(
      issuerAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      logoUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getIssuerByAddress(
      issuerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerIssuer(
      issuerAddress: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      logoUrl: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
