/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as endpoints from "./endpoints";
export * as nft from "./nft";
export * as storage from "./storage";
