/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccreditationStorage__factory } from "./AccreditationStorage__factory";
export { CertificateStorage__factory } from "./CertificateStorage__factory";
