/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ApplicantStorage__factory } from "./ApplicantStorage__factory";
export { IssuerStorage__factory } from "./IssuerStorage__factory";
