/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccreditationNFT__factory } from "./AccreditationNFT__factory";
export { CertificateNFT__factory } from "./CertificateNFT__factory";
