/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ApplicantStorage } from "./ApplicantStorage";
export type { IssuerStorage } from "./IssuerStorage";
